---
# File: roles_example/roles/aws-ec2/tasks/main.yml

- name: Install Git
  yum: name=git state=present

- name: Create a directory
  file: path={{ ansible_env["HOME"]}}/ads state="directory"

- name: Checkout a repo
  git: repo=https://github.com/bjk7706/ansible-repo.git dest={{ ansible_env["HOME"]}}/ansible-repo
 
